### ISSUE TITLE
Warning for snackbar mutation

### ISSUE THREAD

**Issue by derweise** [jeffreybiles/vue-screencasts#1]
I get warning for snackbar:

`[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."`

The warning appears at the end of the snackbar after timeout

**Comment by jeffreybiles** [comment]
Solved in [the course on VueX Strict Mode](https://www.vuescreencasts.com/courses/30)
